### PR TITLE
MNT:Added amostra to auto-build.Both client and server is in the same package

### PR DESCRIPTION
**Pull request by arkilic**
Per discussed with @ericdill, made amostra part of collection and analysis environments until a server conda env is in place.

### CODE REVIEW

**Comment by ericdill** [comment]
Failed because PRs from forks have access to encrypted env vars

**Comment by ericdill** [comment]
Bump the build number please

**Comment by ericdill** [comment]
I'll bump the build number locally and push it up

**Comment by arkilic** [comment]
Thanks @ericdill

**Pull request merged**
