### PR TITLE
bluesky, mds, pyepics tags

### PR DESCRIPTION
**Pull request by tacaswell**
@ericdill I was already working on this.  I need to go to a beamline, can you please sort the conflicts out?

### CODE REVIEW

**Comment by tacaswell** [comment]
The critical one here is the pyecis soft-tag.

**Comment by ericdill** [comment]
Yes I will deal with this in a bit.  Definitely by lunch

**Comment by ericdill** [comment]
I am going to complain that you are making a soft tag on `nsls2-tag` that is identical to what is available on `nsls2-dev` and then will make this recipe work for you anyway.

**Comment by ericdill** [comment]
All of these recipes are in #12 .  Once that build passes on circle-ci, I will merge it in, or feel free to merge it yourself after the build passes if I am not paying close enough attention to do it immediately

**Comment by tacaswell** [comment]
I would like this merged it time for the 11 o'clock auto build.

**Pull request closed without merging**
