### PR TITLE
ffmpeg is not building on the controls network

### PR DESCRIPTION
**Pull request by ericdill**
Getting the following error for ffmpeg:

'fatal: unable to connect to source.ffmpeg.org:\n'
 'source.ffmpeg.org: Name or service not known\n'

### CODE REVIEW

**Comment by ericdill** [comment]
@stuwilkins any idea if it is possible to access `git://source.ffmpeg.org/ffmpeg.git` from the controls network?  `git clone git://source.ffmpeg.org/ffmpeg.git` fails behind the nsls2 firewall

**Comment by stuwilkins** [comment]
HI @ericdill I don't think that the git protocol will make it through the firewalls. Can you use http access for ffmpeg? 

What about using [this mirror](https://github.com/FFmpeg/FFmpeg) and then using:

https://github.com/FFmpeg/FFmpeg.git

**Comment by ericdill** [comment]
Now there's a good idea! I'll try that and report back, thanks!!

**Comment by ericdill** [comment]
That fixes it. Thanks @stuwilkins

**Pull request closed without merging**
