### PR TITLE
Add new bluesky, ophyd, databroker versions.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by ericdill** [comment]
Could you modify the 0.4.0rc2 recipe in-place to become 0.4.0?  I made some substantial edits to the meta.yaml to include a number of dependencies to testing and import *all* the modules to make sure they are all importable.  Doing this found at least one bug in bluesky, so I would prefer to have this minimal level of sanity checking before we deploy tagged builds

**Comment by ericdill** [comment]
https://github.com/NSLS-II/auto-build-tagged-recipes/blob/master/py3/bluesky-0.4.0rc2/meta.yaml

**Comment by ericdill** [comment]
(Note that I am also happy to take over and just make this work if you would rather be doing other stuff)

**Comment by ericdill** [comment]
databroker and ophyd look good, thanks!

**Comment by ericdill** [comment]
Thanks @danielballan ; I took over and did the bluesky modifications I suggested above.  These builds should be available in ~30 minutes

**Comment by danielballan** [comment]
Thanks again.

**Pull request merged**
