### PR TITLE
Add databroker v0.4.0

### PR DESCRIPTION
**Pull request by danielballan**
* Removed old databroker recipes
* Changed 0.3.3 -> 0.4.0
* Added requests dep and specified min MDS version as 0.4.1 (where text index was introduced)

### CODE REVIEW

**Comment by ericdill** [comment]
You've got an extra meta.yaml file in databroker-0.4.0/. Also change the version numbers in the meta.yaml that you want to keep to 0.4.0

**Comment by danielballan** [comment]
Oops. Someone a garbage file got committed. Sorry.

**Comment by danielballan** [comment]
Should be good now.

**Comment by ericdill** [comment]
LGTM Thanks

**Pull request merged**
